name: Patch Release

on:
  push:
    branches:
      - master

permissions:
  contents: write  # Needed to push tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to get tags

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump patch version and create tag
        id: bump_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

