name: CI

on:
   push:
    branches:
      - '*'
   pull_request:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Helm repo
        run: |
          echo 'helm repo login openonnovationai demo.harbor.com' 
      
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login demo.goharbor.io/openinnovationai  -u $DOCKER_USERNAME --password-stdin

      - name: Compliance check
        run: |
          echo 'Compliance check using repo policies'
          echo 'helm conftest charts/frontend -p policies'

      - name: Application Build
        run: |
          echo 'Building application'
          echo 'yarn build'

      - name: Unit test
        run: |
          echo 'Running unit test'
          echo 'yarn test'

      - name: Create and push Dockerfile
        run: |
          docker build -t demo.goharbor.io/openinnovationai/frontend:master Dockerfile
          docker tag demo.goharbor.io/openinnovationai/frontend:master demo.goharbor.io/openinnovationai/frontend:master-$GITHUB_SHA
          docker push demo.goharbor.io/openinnovationai/frontend:master
          docker push demo.goharbor.io/openinnovationai/frontend:master--$GITHUB_SHA

      - name: Deploy the application
        run: |
          'helm upgrade -i frontend charts/frontend --debug'
          echo 'We can pass the configuration with whitelisting all the github action ips on out kubenrtes cluster so this action can execute properly'

      # - name: Run unit tests, Docker build, and compliance check in parallel
      #   run: |
      #     # Run unit tests
      #     echo "Running unit tests..."

      #     # Build Docker image
      #     echo "Building Docker image..."
      #     # docker build -t my-docker-image .

      #     # Run compliance check
      #     echo "Running compliance check..."
      #     # Run compliance check commands here

      # - name: Deploy application
      #   run: |
      #     # Deploy application using Helm
      #     # helm upgrade --install my-app ./helm-chart

      # - name: Publish results
      #   run: |
      #     # Publish results
      #     # Add commands to publish results here

      # - name: Clean up
      #   run: |
      #     # Clean up resources
      #     # Add cleanup commands here
